const productosCloset = {
    lista: [
        {
            id: 1,
            img:"/images/productos/1.webp",
            nombre: "Remera con Bordado",
            descripcion: "Remera elegante con apliques dorados",
            descripcionDetallada: "Es una remera negra con un diseño elegante y casual a la vez. Su tela es suave y fresca a pesar de la lycra, se adapta a la figura sin ser demasiado ajustado. Sus apliques bordados son sutiles pero llamativos. Perfecta para combinar con jeans, pantalones sastreros o faldas.",
            estado: "Usado, como nuevo",
            material: "Algodón y lycra",
            categoria: "Mujer",            
            talle: "M",
            precio: "6000",

        }, {
            id: 2,
            img:"/images/productos/2.jpg",
            nombre: "Camisaco Abrigado",
            descripcion: "Camisaco escoces azul y beige, con cierre, tipo campera",
            estado: "Usado, buen estado",
            material: "Lana de algodón",
            categoria: "Hombre",            
            talle: "XL",
            precio: "10000",
        }, {
            id: 3,
            img:"/images/productos/3.webp",
            nombre: "Jean Mom",
            descripcion: "Jean estilo Mom con roturas",
            estado: "Usado, buen estado",
            material: "Jean",
            categoria: "Mujer",            
            talle: "M",
            precio: "10000",
        }, {
            id: 4,
            img:"/images/productos/4.webp",
            nombre: "Remera Nevada Estampada",
            descripcion: "Remera de moda con efecto 'nevado' con estampado",
            estado: "Usado, como nuevo",
            material: "Algodón 100%",
            categoria: "Mujer",            
            talle: "L",
            precio: "8000",
        }, {
            id: 5,
            img:"/images/productos/5.jpg",
            nombre: "Campera Vintage 90's",
            descripcion: "Campera con forro, estilo noventosa de colores vibrantes",
            estado: "Usado, buen estado",
            material: "Tela rompeviento",
            categoria: "Mujer",            
            talle: "XL",
            precio: "12000",
        }, {
            id: 6,
            img:"/images/productos/6.jpg",
            nombre: "Jean Baggy",
            descripcion: "Jean de moda amplio tipo baggy",
            estado: "Nuevo",
            material: "Jean",
            categoria: "Hombre",            
            talle: "L",
            precio: "15000",
        }, {
            id: 7,
            img:"/images/productos/7.jpg",
            nombre: "Campera de Montaña",
            descripcion: "Campera con forro tipo Montagne, abrigada e impermeable",
            estado: "Usado, como nuevo",
            material: "Tela impermeable y polar",
            categoria: "Mujer",            
            talle: "L",
            precio: "20000",
        }, {
            id: 8,
            img:"/images/productos/8.jpg",
            nombre: "Campera University",
            descripcion: "Campera tipo universitaria amplia y abrigada",
            categoria: "Hombre",            
            talle: "M",
            precio: "10000",
        },
        {
            id: 9,
            img:"/images/productos/9.jpeg",
            nombre: "Campera Aviadora",
            descripcion: "Chaqueta marrón con un estilo vintage y robusto",
            descripcionDetallada: "Chaqueta simil cuero marrón con diseño oversized le da un aspecto relajado y cómodo. Los detalles de la chaqueta incluyen costuras visibles en un tono más claro que el cuero, lo que añade un toque de contraste y refuerza su apariencia robusta. Su cuello es desmontable",
            estado: "Nuevo",
            estado: "Usado, como nuevo",
            material: "Simil Cuero",
            categoria: "Hombre",            
            talle: "Oversize",
            precio: "50000",
        }
    ]
}

module.exports = productosCloset;